apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 5
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: chestnutchen/todo-app:v2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"