apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Maximum number of pods that can be unavailable during the update
      maxSurge: 1        # Maximum number of pods that can be created over the desired number
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: chestnutchen/todo-app:v2
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://todo-mongodb:27017/todo"